# Generated by Django 5.2.3 on 2025-06-26 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(default='000000000', max_length=20, unique=True)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('DPI', 'Documento Personal de Identificación'), ('CE', 'Cédula de extranjería'), ('TI', 'Tarjeta de identidad'), ('PA', 'Pasaporte')], default='DPI', max_length=6)),
                ('nombres', models.CharField(default='Desconocido', max_length=100)),
                ('apellidos', models.CharField(default='Paciente', max_length=100)),
                ('telefono_consultorio', models.CharField(default='0000000000', max_length=20)),
                ('celular', models.CharField(default='0000000000', max_length=20)),
                ('codigo_laboratorio', models.CharField(default='XXXXX0', max_length=20)),
                ('email', models.EmailField(default='sin@email.com', max_length=254)),
                ('direccion_consultorio', models.TextField(default='Sin dirección')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='M', max_length=1)),
                ('especialidad_medica', models.CharField(choices=[('GEN', 'Medicina General'), ('PED', 'Pediatría'), ('GIN', 'Ginecología'), ('DER', 'Dermatología'), ('CAR', 'Cardiología'), ('NEU', 'Neurología'), ('NEURO', 'Neumología'), ('END', 'Endocrinología'), ('OFT', 'Oftalmología'), ('OTO', 'Otorrinolaringología'), ('TRA', 'Traumatología'), ('URO', 'Urología'), ('PSI', 'Psiquiatría'), ('ODO', 'Odontología'), ('REU', 'Reumatología'), ('GAS', 'Gastroenterología'), ('ONC', 'Oncología'), ('HEM', 'Hematología'), ('CIR', 'Cirugía General'), ('CIRP', 'Cirugía Pediátrica'), ('CIRC', 'Cirugía Cardiovascular'), ('RAD', 'Radiología'), ('INT', 'Medicina Interna'), ('FOR', 'Medicina Forense'), ('ANE', 'Anestesiología')], default='GEN', max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='localizacion.municipio')),
            ],
        ),
    ]
