# Generated by Django 5.2.3 on 2025-06-19 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='ocupacion',
        ),
    ]
