# Generated by Django 5.2.3 on 2025-10-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoUnidadParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único de la unidad (ej: GDL, MUL, KUL)', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre de la unidad (ej: Gramos por decilitro)', max_length=100)),
                ('simbolo', models.CharField(help_text='Símbolo de la unidad (ej: g/dL, M/μL, K/μL)', max_length=20)),
                ('categoria', models.CharField(help_text='Categoría de la unidad (ej: Hematología, Química, Microbiología)', max_length=50)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la unidad')),
                ('activo', models.BooleanField(default=True, help_text='Indica si esta unidad está activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Unidad de Parámetro',
                'verbose_name_plural': 'Unidades de Parámetros',
                'ordering': ['categoria', 'nombre'],
                'indexes': [models.Index(fields=['categoria'], name='catalogos_c_categor_fe8b9e_idx'), models.Index(fields=['activo'], name='catalogos_c_activo_d155b2_idx')],
            },
        ),
    ]
