# Generated by Django 5.2.3 on 2025-10-25 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('valor', models.FloatField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('pacientes', 'Pacientes'), ('examenes', 'Exámenes'), ('resultados', 'Resultados'), ('financiero', 'Financiero'), ('operativo', 'Operativo')], max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Métrica del Dashboard',
                'verbose_name_plural': 'Métricas del Dashboard',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='DashboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuracion', models.JSONField(default=dict)),
                ('tema', models.CharField(choices=[('claro', 'Claro'), ('oscuro', 'Oscuro'), ('auto', 'Automático')], default='auto', max_length=20)),
                ('actualizacion_automatica', models.BooleanField(default=True)),
                ('intervalo_actualizacion', models.IntegerField(default=30)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración del Dashboard',
                'verbose_name_plural': 'Configuraciones del Dashboard',
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('grafico', 'Gráfico'), ('metrica', 'Métrica'), ('tabla', 'Tabla'), ('lista', 'Lista')], max_length=50)),
                ('configuracion', models.JSONField(default=dict)),
                ('posicion_x', models.IntegerField(default=0)),
                ('posicion_y', models.IntegerField(default=0)),
                ('ancho', models.IntegerField(default=4)),
                ('alto', models.IntegerField(default=3)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Widget del Dashboard',
                'verbose_name_plural': 'Widgets del Dashboard',
                'ordering': ['posicion_y', 'posicion_x'],
            },
        ),
    ]
