# Generated by Django 5.2.3 on 2025-08-14 22:36

import django.db.models.deletion
import resultados.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('validado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_resultado', models.DateField(default=resultados.models.get_today_date)),
                ('fecha_validacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('VALIDADO', 'Validado'), ('EN PROCESO', 'En Proceso')], default='PENDIENTE', max_length=20)),
                ('prioridad', models.CharField(default='normal', max_length=20)),
                ('resultado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='ordenes.detalleorden')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=50)),
                ('unidad', models.CharField(max_length=20)),
                ('rango_normal', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=20)),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='resultados.resultado')),
            ],
        ),
    ]
