# Generated by Django 5.2.3 on 2025-07-19 03:35

import resultados.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='fecha_resultado',
            field=models.DateField(default=resultados.models.get_today_date),
        ),
    ]
