# Generated by Django 5.2.3 on 2025-08-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0002_alter_resultado_fecha_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('VALIDADO', 'Validado'), ('EN PROCESO', 'En Proceso')], default='PENDIENTE', max_length=20),
        ),
    ]
