# Generated by Django 5.2.3 on 2025-10-21 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0003_alter_resultado_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoMotivoDenegacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del motivo', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del motivo de denegación', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del motivo')),
                ('activo', models.BooleanField(default=True, help_text='Indica si este motivo está activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Motivo de Denegación',
                'verbose_name_plural': 'Motivos de Denegación',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='resultado',
            name='observaciones_denegacion',
            field=models.TextField(blank=True, help_text='Observaciones adicionales sobre la denegación', null=True),
        ),
        migrations.AddField(
            model_name='resultado',
            name='motivo_denegacion',
            field=models.ForeignKey(blank=True, help_text='Motivo por el cual se deniega la aptitud del donante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_denegados', to='resultados.catalogomotivodenegacion'),
        ),
    ]
