# Generated by Django 5.2.3 on 2025-10-21 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_sangre', '0011_remove_salidaunidad_cedula_receptor_and_more'),
        ('ordenes', '0004_orden_continuar_entrevista'),
        ('resultados', '0004_catalogomotivodenegacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialDenegacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales de la denegación', null=True)),
                ('usuario_deniego', models.CharField(help_text='Usuario que realizó la denegación', max_length=100)),
                ('fecha_denegacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la denegación')),
                ('resultado_examen', models.CharField(help_text='Nombre del examen que generó la denegación', max_length=200)),
                ('valores_criticos', models.JSONField(blank=True, default=dict, help_text='Valores críticos que motivaron la denegación')),
                ('donante', models.ForeignKey(help_text='Donante que fue denegado', on_delete=django.db.models.deletion.CASCADE, related_name='historial_denegaciones', to='banco_sangre.donante')),
                ('motivo_denegacion', models.ForeignKey(help_text='Motivo por el cual se denegó', on_delete=django.db.models.deletion.PROTECT, related_name='historial_uso', to='resultados.catalogomotivodenegacion')),
                ('orden', models.ForeignKey(help_text='Orden asociada a la denegación', on_delete=django.db.models.deletion.CASCADE, related_name='historial_denegaciones', to='ordenes.orden')),
                ('resultado', models.ForeignKey(help_text='Resultado que generó la denegación', on_delete=django.db.models.deletion.CASCADE, related_name='historial_denegaciones', to='resultados.resultado')),
            ],
            options={
                'verbose_name': 'Historial de Denegación',
                'verbose_name_plural': 'Historial de Denegaciones',
                'ordering': ['-fecha_denegacion'],
                'indexes': [models.Index(fields=['donante', '-fecha_denegacion'], name='resultados__donante_1cfe12_idx'), models.Index(fields=['motivo_denegacion'], name='resultados__motivo__f2aded_idx')],
            },
        ),
    ]
