# Generated by Django 5.2.3 on 2025-10-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0005_historialdenegacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogomotivodenegacion',
            options={'ordering': ['tipo_denegacion', 'codigo'], 'verbose_name': 'Motivo de Denegación', 'verbose_name_plural': 'Motivos de Denegación'},
        ),
        migrations.AddField(
            model_name='catalogomotivodenegacion',
            name='tiempo_diferimiento_dias',
            field=models.IntegerField(blank=True, help_text='Días de diferimiento para denegaciones temporales (ej: 90, 365)', null=True),
        ),
        migrations.AddField(
            model_name='catalogomotivodenegacion',
            name='tipo_denegacion',
            field=models.CharField(choices=[('PERMANENTE', 'Permanente - Nunca podrá donar'), ('TEMPORAL', 'Temporal - Puede donar después')], default='TEMPORAL', help_text='Tipo de denegación: Permanente o Temporal', max_length=20),
        ),
    ]
