# Generated by Django 5.2.3 on 2025-06-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_laboratorio', models.CharField(max_length=255)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('enviar_resultados', models.BooleanField(default=False)),
                ('enviar_notificaciones', models.BooleanField(default=False)),
                ('servidor_smtp', models.CharField(blank=True, max_length=255)),
                ('puerto_smtp', models.CharField(blank=True, max_length=10)),
                ('usuario_smtp', models.CharField(blank=True, max_length=255)),
                ('password_smtp', models.CharField(blank=True, max_length=255)),
                ('formato_pdf', models.CharField(default='A4', max_length=20)),
                ('mostrar_logo', models.BooleanField(default=True)),
                ('mostrar_firma', models.BooleanField(default=True)),
                ('color_encabezado', models.CharField(default='#1976d2', max_length=20)),
                ('pie_pagina', models.CharField(blank=True, max_length=255)),
                ('backup_automatico', models.BooleanField(default=False)),
                ('frecuencia_backup', models.CharField(default='diario', max_length=20)),
                ('hora_backup', models.TimeField(default='03:00')),
                ('ruta_backup', models.CharField(default='/backups', max_length=255)),
            ],
        ),
    ]
