# Generated by Django 5.2.3 on 2025-06-21 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date(2025, 6, 21)),
        ),
    ]
