# Generated by Django 5.2.3 on 2025-06-22 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0002_alter_examen_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date(2025, 6, 22)),
        ),
    ]
