# Generated by Django 5.2.3 on 2025-08-14 22:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMuestra',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('correlativo', models.CharField(blank=True, max_length=30, unique=True)),
                ('tipo_unidad', models.CharField(choices=[('PLASMA', 'Plasma'), ('PAQUETE_GLOBULAR', 'Paquete Globular'), ('PLAQUETAS', 'Plaquetas'), ('CRIO_PRECIPITADO', 'Crio Precipitado')], max_length=50)),
                ('tipo_sangre', models.CharField(max_length=5)),
                ('volumen_ml', models.PositiveIntegerField()),
                ('fecha_extraccion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_donacion', models.DateField(blank=True, null=True)),
                ('fecha_validacion', models.DateField(blank=True, null=True)),
                ('fecha_caducidad', models.DateField()),
                ('localizacion', models.CharField(blank=True, max_length=100)),
                ('condiciones_almacenamiento', models.CharField(blank=True, max_length=200)),
                ('serologias', models.JSONField(blank=True, default=dict)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('VENCIDO', 'Vencido'), ('DESCARTADO', 'Descartado'), ('TRANSFORMADA', 'Transformada')], default='DISPONIBLE', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_extraccion'],
            },
        ),
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cui', models.CharField(max_length=50, unique=True)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('sexo', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('ocupacion', models.CharField(default='Sin especificar', max_length=100)),
                ('apto_donacion', models.BooleanField(default=False)),
                ('tiene_entrevista_apro', models.BooleanField(default=False)),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='localizacion.municipio')),
            ],
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.CharField(max_length=50, unique=True)),
                ('cui', models.CharField(max_length=50)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('sexo', models.CharField(max_length=20)),
                ('grupo_etnico', models.CharField(blank=True, max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.PositiveIntegerField()),
                ('lugar_nacimiento', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('ocupacion', models.CharField(max_length=100)),
                ('comunidad_linguistica', models.CharField(blank=True, max_length=100)),
                ('estado_civil', models.CharField(max_length=50)),
                ('direccion_casa', models.CharField(max_length=200)),
                ('telefono_casa', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion_trabajo', models.CharField(blank=True, max_length=200)),
                ('telefono_trabajo', models.CharField(blank=True, max_length=20)),
                ('tipo_sangre', models.CharField(max_length=5)),
                ('peso', models.FloatField()),
                ('pulso', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('hemoglobina', models.FloatField()),
                ('presion_sistolica', models.FloatField()),
                ('presion_diastolica', models.FloatField()),
                ('hematocrito', models.FloatField()),
                ('respuestas_entrevista', models.JSONField(default=dict)),
                ('respuestas_adicionales_entrevista', models.JSONField(default=dict)),
                ('respuestas_medicas_adicionales', models.JSONField(default=dict)),
                ('respuestas_mujeres', models.JSONField(blank=True, null=True)),
                ('consentimiento_informado', models.BooleanField(default=False)),
                ('nombre_entrevistador', models.CharField(max_length=100)),
                ('firma_donador', models.TextField()),
                ('firma_entrevistador', models.TextField()),
                ('hora_inicio_flebotomia', models.TimeField()),
                ('hora_finalizacion_flebotomia', models.TimeField()),
                ('cantidad_sangre', models.PositiveIntegerField()),
                ('reacciones_adversas', models.BooleanField()),
                ('observaciones_flebotomia', models.TextField(blank=True)),
                ('nombre_flebotomista', models.CharField(max_length=100)),
                ('firma_flebotomista', models.TextField()),
                ('fecha', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='pendiente', max_length=50)),
                ('pdf_entrevista', models.FileField(blank=True, null=True, upload_to='entrevistas/')),
                ('donante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrevistas', to='banco_sangre.donante')),
            ],
        ),
    ]
