# Generated by Django 5.2.3 on 2025-07-07 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cui', models.CharField(max_length=50, unique=True)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('sexo', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MuestraSangre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.CharField(max_length=50, unique=True)),
                ('tipo_unidad', models.CharField(max_length=50)),
                ('tipo_sangre', models.CharField(max_length=5)),
                ('volumen_ml', models.PositiveIntegerField()),
                ('fecha_extraccion', models.DateField()),
                ('fecha_donacion', models.DateField(blank=True, null=True)),
                ('fecha_validacion', models.DateField(blank=True, null=True)),
                ('fecha_caducidad', models.DateField()),
                ('lote', models.CharField(blank=True, max_length=50)),
                ('localizacion', models.CharField(blank=True, max_length=100)),
                ('condiciones_almacenamiento', models.CharField(blank=True, max_length=200)),
                ('serologias', models.JSONField(blank=True, default=dict)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Reservado', 'Reservado'), ('Vencido', 'Vencido'), ('Descartado', 'Descartado')], max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.CharField(max_length=50, unique=True)),
                ('cui', models.CharField(max_length=50)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('sexo', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.PositiveIntegerField()),
                ('doctor', models.CharField(max_length=100)),
                ('donador_de', models.CharField(blank=True, max_length=100)),
                ('fecha', models.DateField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('donante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrevistas', to='banco_sangre.donante')),
            ],
        ),
    ]
