# Generated by Django 5.2.3 on 2025-07-08 15:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_sangre', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMuestra',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('correlativo', models.CharField(blank=True, max_length=30, unique=True)),
                ('tipo_unidad', models.CharField(choices=[('PLASMA', 'Plasma'), ('PAQUETE_GLOBULAR', 'Paquete Globular'), ('PLAQUETAS', 'Plaquetas'), ('CRIO_PRECIPITADO', 'Crio Precipitado')], max_length=50)),
                ('tipo_sangre', models.CharField(max_length=5)),
                ('volumen_ml', models.PositiveIntegerField()),
                ('fecha_extraccion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_caducidad', models.DateField()),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('VENCIDO', 'Vencido')], default='DISPONIBLE', max_length=20)),
                ('donante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades', to='banco_sangre.donante')),
            ],
            options={
                'ordering': ['-fecha_extraccion'],
            },
        ),
    ]
