# Generated by Django 5.2.3 on 2025-08-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_sangre', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrevista',
            name='pdf_entrevista',
            field=models.FileField(blank=True, null=True, upload_to='entrevistas/'),
        ),
    ]
