# Generated by Django 5.2.3 on 2025-08-14 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_sangre', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadmuestra',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('VENCIDO', 'Vencido'), ('DESCARTADO', 'Descartado'), ('TRANSFORMADA', 'Transformada'), ('ENTREGADA', 'Entregada')], default='DISPONIBLE', max_length=20),
        ),
        migrations.CreateModel(
            name='SalidaUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receptor', models.CharField(help_text='Nombre del receptor', max_length=200)),
                ('cedula_receptor', models.CharField(help_text='Cédula del receptor', max_length=20)),
                ('medico_solicitante', models.CharField(help_text='Nombre del médico solicitante', max_length=200)),
                ('fecha_salida', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('correlativo', models.CharField(blank=True, max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('pdf_salida', models.FileField(blank=True, null=True, upload_to='salidas/')),
                ('firma_receptor', models.TextField(blank=True)),
                ('firma_tecnico', models.TextField(blank=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('tecnico_salida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inclusion', models.DateTimeField(auto_now_add=True)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='banco_sangre.unidadmuestra')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='banco_sangre.salidaunidad')),
            ],
            options={
                'unique_together': {('salida', 'unidad')},
            },
        ),
    ]
