# Generated by Django 5.2.3 on 2025-07-08 15:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_sangre', '0003_unidadmuestra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmuestra',
            name='condiciones_almacenamiento',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='unidadmuestra',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidadmuestra',
            name='fecha_donacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidadmuestra',
            name='fecha_validacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unidadmuestra',
            name='localizacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='unidadmuestra',
            name='lote',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='unidadmuestra',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unidadmuestra',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unidadmuestra',
            name='serologias',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='unidadmuestra',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('VENCIDO', 'Vencido'), ('DESCARTADO', 'Descartado')], default='DISPONIBLE', max_length=20),
        ),
        migrations.DeleteModel(
            name='MuestraSangre',
        ),
    ]
