# Generated by Django 5.2.3 on 2025-08-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_sangre', '0003_alter_unidadmuestra_estado_salidaunidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donante',
            name='codigo_donante',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='donante',
            name='fecha_ultima_donacion',
            field=models.DateField(blank=True, help_text='Fecha de la última donación', null=True),
        ),
        migrations.AddField(
            model_name='donante',
            name='historial_codigos',
            field=models.JSONField(blank=True, default=list, help_text='Historial de códigos del donante'),
        ),
    ]
