# Generated by Django 5.2.3 on 2025-08-06 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco_sangre', '0003_entrevista_pdf_entrevista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrevista',
            name='direccion',
        ),
    ]
