# Generated by Django 5.2.3 on 2025-08-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_sangre', '0004_donante_codigo_donante_donante_fecha_ultima_donacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmuestra',
            name='etiqueta_pdf',
            field=models.FileField(blank=True, help_text='PDF de la etiqueta generada automáticamente', null=True, upload_to='etiquetas/'),
        ),
    ]
