# Generated by Django 5.2.3 on 2025-08-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_sangre', '0004_remove_entrevista_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrevista',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
