# Generated by Django 5.2.3 on 2025-07-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_sangre', '0005_lote_alter_unidadmuestra_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='donante',
            name='ocupacion',
            field=models.CharField(default='Sin especificar', max_length=100),
        ),
    ]
