# Generated by Django 5.2.3 on 2025-09-04 04:16

import django.db.models.deletion
from django.db import migrations, models


def populate_codigo_donante_muestra(apps, schema_editor):
    """
    Poblar el campo codigo_donante_muestra para registros existentes
    """
    UnidadMuestra = apps.get_model('banco_sangre', 'UnidadMuestra')
    
    # Para registros existentes sin orden, generar un código temporal
    for unidad in UnidadMuestra.objects.filter(codigo_donante_muestra__isnull=True):
        if unidad.orden and unidad.donante:
            # Generar código basado en la orden
            orden_id = unidad.orden.id
            # Buscar el último código para esta orden
            ultimo_codigo = UnidadMuestra.objects.filter(
                orden=unidad.orden,
                codigo_donante_muestra__startswith=f'DON-{orden_id}-'
            ).order_by('-codigo_donante_muestra').first()
            
            if ultimo_codigo:
                try:
                    ultimo_numero = int(ultimo_codigo.codigo_donante_muestra.split('-')[-1])
                    nuevo_numero = ultimo_numero + 1
                except (ValueError, IndexError):
                    nuevo_numero = 1
            else:
                nuevo_numero = 1
            
            unidad.codigo_donante_muestra = f'DON-{orden_id}-{nuevo_numero:03d}'
        else:
            # Para registros sin orden, usar un código temporal
            unidad.codigo_donante_muestra = f'TEMP-{unidad.id:06d}'
        
        unidad.save(update_fields=['codigo_donante_muestra'])


def reverse_populate_codigo_donante_muestra(apps, schema_editor):
    """
    Revertir la población del campo codigo_donante_muestra
    """
    UnidadMuestra = apps.get_model('banco_sangre', 'UnidadMuestra')
    UnidadMuestra.objects.all().update(codigo_donante_muestra='')


class Migration(migrations.Migration):

    dependencies = [
        ('banco_sangre', '0005_alter_entrevista_fecha_creacion'),
        ('ordenes', '0004_orden_continuar_entrevista'),
    ]

    operations = [
        # Paso 1: Agregar el campo orden sin restricciones
        migrations.AddField(
            model_name='unidadmuestra',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_muestra', to='ordenes.orden'),
        ),
        
        # Paso 2: Agregar el campo codigo_donante_muestra sin restricción única inicialmente
        migrations.AddField(
            model_name='unidadmuestra',
            name='codigo_donante_muestra',
            field=models.CharField(blank=True, help_text='Código único del donante para esta muestra específica por orden', max_length=50, null=True),
        ),
        
        # Paso 3: Poblar los datos existentes
        migrations.RunPython(
            populate_codigo_donante_muestra,
            reverse_populate_codigo_donante_muestra,
        ),
        
        # Paso 4: Hacer el campo no nulo
        migrations.AlterField(
            model_name='unidadmuestra',
            name='codigo_donante_muestra',
            field=models.CharField(blank=True, help_text='Código único del donante para esta muestra específica por orden', max_length=50),
        ),
        
        # Paso 5: Agregar la restricción única
        migrations.AlterField(
            model_name='unidadmuestra',
            name='codigo_donante_muestra',
            field=models.CharField(blank=True, help_text='Código único del donante para esta muestra específica por orden', max_length=50, unique=True),
        ),
    ]
