# Generated by Django 5.2.3 on 2025-09-04 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_sangre', '0006_unidadmuestra_codigo_donante_muestra_and_more'),
        ('ordenes', '0004_orden_continuar_entrevista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadmuestra',
            name='codigo_donante_muestra',
        ),
        migrations.RemoveField(
            model_name='unidadmuestra',
            name='orden',
        ),
        migrations.CreateModel(
            name='CodigoDonante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del donante para una orden específica', max_length=50, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si este código está activo para la orden')),
                ('donante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_donante', to='banco_sangre.donante')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_donante', to='ordenes.orden')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'unique_together': {('donante', 'orden')},
            },
        ),
        migrations.AddField(
            model_name='unidadmuestra',
            name='codigo_donante',
            field=models.ForeignKey(blank=True, help_text='Código del donante asociado a esta muestra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_muestra', to='banco_sangre.codigodonante'),
        ),
    ]
