# Generated by Django 5.2.3 on 2025-07-12 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_sangre', '0006_donante_ocupacion'),
        ('localizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donante',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='localizacion.municipio'),
        ),
    ]
