# Generated by Django 5.2.3 on 2025-09-17 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_sangre', '0007_remove_unidadmuestra_codigo_donante_muestra_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoDescarte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del motivo de descarte', max_length=10, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del motivo de descarte', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del motivo')),
                ('activo', models.BooleanField(default=True, help_text='Indica si esta opción está disponible')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catálogo de Descarte',
                'verbose_name_plural': 'Catálogos de Descarte',
                'ordering': ['codigo'],
            },
        ),
        migrations.AlterField(
            model_name='unidadmuestra',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('VENCIDO', 'Vencido'), ('DESCARTADO', 'Descartado'), ('TRANSFORMADA', 'Transformada'), ('EN_DESCARTE', 'En Proceso de Descarte')], default='DISPONIBLE', max_length=20),
        ),
        migrations.CreateModel(
            name='DescarteMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales del descarte')),
                ('fecha_descarte', models.DateTimeField(auto_now_add=True)),
                ('validado', models.BooleanField(default=False, help_text='Indica si el descarte ha sido validado')),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.ForeignKey(help_text='Motivo del descarte', on_delete=django.db.models.deletion.PROTECT, to='banco_sangre.catalogodescarte')),
                ('muestra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='descarte', to='banco_sangre.unidadmuestra')),
                ('responsable', models.ForeignKey(blank=True, help_text='Usuario que realizó el descarte', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('validador', models.ForeignKey(blank=True, help_text='Usuario que validó el descarte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descartes_validados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Descarte de Muestra',
                'verbose_name_plural': 'Descartes de Muestras',
                'ordering': ['-fecha_descarte'],
            },
        ),
    ]
