# Generated by Django 5.2.3 on 2025-10-07 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_sangre', '0008_catalogodescarte_alter_unidadmuestra_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmuestra',
            name='es_transformacion',
            field=models.BooleanField(default=False, help_text='Indica si esta muestra es resultado de una transformación'),
        ),
        migrations.AddField(
            model_name='unidadmuestra',
            name='muestra_padre',
            field=models.ForeignKey(blank=True, help_text='Muestra original de la cual se transformó esta muestra', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muestras_hijas', to='banco_sangre.unidadmuestra'),
        ),
        migrations.AlterField(
            model_name='unidadmuestra',
            name='correlativo',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
