# Generated by Django 5.2.3 on 2025-07-15 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_sangre', '0008_alter_unidadmuestra_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadmuestra',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('VENCIDO', 'Vencido'), ('DESCARTADO', 'Descartado'), ('TRANSFORMADA', 'Transformada')], default='DISPONIBLE', max_length=20),
        ),
    ]
