# Generated by Django 5.2.3 on 2025-10-17 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_sangre', '0009_add_transformacion_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.CharField(blank=True, help_text='Correlativo único de la salida', max_length=50, unique=True)),
                ('receptor', models.CharField(help_text='Nombre completo de quien recibe las unidades', max_length=200)),
                ('cedula_receptor', models.CharField(help_text='Cédula/DPI del receptor', max_length=20)),
                ('medico_solicitante', models.CharField(help_text='Nombre del médico que solicita', max_length=200)),
                ('fecha_salida', models.DateTimeField(help_text='Fecha y hora de la salida')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales')),
                ('tecnico_nombre', models.CharField(blank=True, help_text='Nombre del técnico', max_length=200)),
                ('cantidad_unidades', models.PositiveIntegerField(default=0, help_text='Cantidad total de unidades en la salida')),
                ('pdf_salida', models.FileField(blank=True, help_text='PDF de la salida', null=True, upload_to='salidas/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('tecnico', models.ForeignKey(blank=True, help_text='Técnico que registra la salida', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salida de Unidad',
                'verbose_name_plural': 'Salidas de Unidades',
                'ordering': ['-fecha_salida'],
            },
        ),
        migrations.CreateModel(
            name='DetalleaSalidaUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_muestra', models.ForeignKey(help_text='Unidad de muestra', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_salida', to='banco_sangre.unidadmuestra')),
                ('salida', models.ForeignKey(help_text='Salida a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='banco_sangre.salidaunidad')),
            ],
            options={
                'verbose_name': 'Detalle de Salida',
                'verbose_name_plural': 'Detalles de Salida',
                'unique_together': {('salida', 'unidad_muestra')},
            },
        ),
    ]
