# Generated by Django 5.2.3 on 2025-10-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_sangre', '0010_salidaunidad_detalleasalidaunidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salidaunidad',
            name='cedula_receptor',
        ),
        migrations.AddField(
            model_name='salidaunidad',
            name='identificador_receptor',
            field=models.CharField(blank=True, help_text='Identificador del receptor (DPI, pasaporte, etc.)', max_length=20),
        ),
    ]
