# Generated by Django 5.2.3 on 2025-10-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_sangre', '0011_remove_salidaunidad_cedula_receptor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donante',
            name='denegado_permanente',
            field=models.BooleanField(default=False, help_text='Indica si el donante tiene denegación permanente y nunca podrá donar'),
        ),
        migrations.AddField(
            model_name='donante',
            name='fecha_denegacion_permanente',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se marcó como denegado permanente', null=True),
        ),
        migrations.AddField(
            model_name='donante',
            name='motivo_denegacion_permanente',
            field=models.TextField(blank=True, help_text='Motivo de la denegación permanente', null=True),
        ),
    ]
