# Generated by Django 5.2.3 on 2025-10-31 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_sangre', '0012_donante_denegado_permanente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadmuestra',
            name='tipo_unidad',
            field=models.CharField(choices=[('PLASMA', 'Plasma'), ('PAQUETE_GLOBULAR', 'Paquete Globular'), ('PLAQUETAS', 'Plaquetas'), ('CRIO_PRECIPITADO', 'Crio Precipitado'), ('PLASMA_AFERESIS', 'Plasma Aferesis'), ('PLAQUETAS_AFERESIS', 'Plaquetas Aferesis')], max_length=50),
        ),
    ]
