# Generated by Django 5.2.3 on 2025-06-20 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0001_initial'),
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='examenes',
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examenes.examen')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.orden')),
            ],
        ),
    ]
