# Generated by Django 5.2.3 on 2025-06-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleorden',
            old_name='resultado',
            new_name='resultado_pdf',
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VALIDADO', 'Validado'), ('CANCELADO', 'Cancelado'), ('ENTREGADO', 'Entregado'), ('EN PROCESO', 'Procesando')], default='PENDIENTE', max_length=20),
        ),
    ]
