# Generated by Django 5.2.3 on 2025-07-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='genero_entrevista',
            field=models.BooleanField(default=False),
        ),
    ]
