# Generated by Django 5.2.3 on 2025-06-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_rename_resultado_detalleorden_resultado_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='prioridad',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('NORMAL', 'Normal')], default='NORMAL', max_length=40),
        ),
    ]
