# Generated by Django 5.2.3 on 2025-06-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0001_initial'),
        ('ordenes', '0002_remove_orden_examenes_detalleorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='examenes',
            field=models.ManyToManyField(related_name='ordenes', through='ordenes.DetalleOrden', to='examenes.examen'),
        ),
    ]
