# Generated by Django 5.2.3 on 2025-06-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_orden_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleorden',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VALIDADO', 'Validado'), ('CANCELADO', 'Cancelado'), ('ENTREGADO', 'Entregado'), ('EN PROCESO', 'Procesando')], default='PENDIENTE', max_length=20),
        ),
    ]
