# Generated by Django 5.2.3 on 2025-08-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_orden_genero_entrevista'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='continuar_entrevista',
            field=models.BooleanField(default=True),
        ),
    ]
